# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(531, 405)
        self.gridLayout_5 = QtWidgets.QGridLayout(Form)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(65, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.comboBox_tableName = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_tableName.sizePolicy().hasHeightForWidth())
        self.comboBox_tableName.setSizePolicy(sizePolicy)
        self.comboBox_tableName.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_tableName.setFont(font)
        self.comboBox_tableName.setObjectName("comboBox_tableName")
        self.gridLayout_2.addWidget(self.comboBox_tableName, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_ProjectName = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_ProjectName.setFont(font)
        self.label_ProjectName.setTextFormat(QtCore.Qt.AutoText)
        self.label_ProjectName.setScaledContents(False)
        self.label_ProjectName.setWordWrap(True)
        self.label_ProjectName.setObjectName("label_ProjectName")
        self.gridLayout.addWidget(self.label_ProjectName, 0, 0, 1, 1)
        self.comboBox_ProjectName = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_ProjectName.setObjectName("comboBox_ProjectName")
        self.gridLayout.addWidget(self.comboBox_ProjectName, 0, 1, 1, 3)
        self.label_TestNumber = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_TestNumber.setFont(font)
        self.label_TestNumber.setWordWrap(True)
        self.label_TestNumber.setObjectName("label_TestNumber")
        self.gridLayout.addWidget(self.label_TestNumber, 0, 4, 1, 1)
        self.comboBox_TestNumber = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_TestNumber.setObjectName("comboBox_TestNumber")
        self.gridLayout.addWidget(self.comboBox_TestNumber, 0, 5, 1, 1)
        self.label_priority = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_priority.setFont(font)
        self.label_priority.setObjectName("label_priority")
        self.gridLayout.addWidget(self.label_priority, 1, 0, 1, 1)
        self.comboBox_priority = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_priority.setObjectName("comboBox_priority")
        self.gridLayout.addWidget(self.comboBox_priority, 1, 1, 1, 3)
        self.label_requirementNumber = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_requirementNumber.setFont(font)
        self.label_requirementNumber.setWordWrap(True)
        self.label_requirementNumber.setObjectName("label_requirementNumber")
        self.gridLayout.addWidget(self.label_requirementNumber, 1, 4, 1, 1)
        self.comboBox_requirementNumber = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_requirementNumber.setObjectName("comboBox_requirementNumber")
        self.gridLayout.addWidget(self.comboBox_requirementNumber, 1, 5, 1, 1)
        self.label_designer = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_designer.setFont(font)
        self.label_designer.setObjectName("label_designer")
        self.gridLayout.addWidget(self.label_designer, 2, 0, 1, 1)
        self.comboBox_designer = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_designer.setObjectName("comboBox_designer")
        self.gridLayout.addWidget(self.comboBox_designer, 2, 1, 1, 1)
        self.label_designTime = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_designTime.setFont(font)
        self.label_designTime.setObjectName("label_designTime")
        self.gridLayout.addWidget(self.label_designTime, 2, 2, 1, 1)
        self.comboBox_designTime = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_designTime.setObjectName("comboBox_designTime")
        self.gridLayout.addWidget(self.comboBox_designTime, 2, 3, 1, 1)
        self.label_requirementModel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_requirementModel.setFont(font)
        self.label_requirementModel.setWordWrap(True)
        self.label_requirementModel.setObjectName("label_requirementModel")
        self.gridLayout.addWidget(self.label_requirementModel, 2, 4, 1, 1)
        self.comboBox_requirementModel = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_requirementModel.setObjectName("comboBox_requirementModel")
        self.gridLayout.addWidget(self.comboBox_requirementModel, 2, 5, 1, 1)
        self.label_TestName = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_TestName.setFont(font)
        self.label_TestName.setWordWrap(True)
        self.label_TestName.setObjectName("label_TestName")
        self.gridLayout.addWidget(self.label_TestName, 3, 0, 1, 1)
        self.comboBox_TestName = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_TestName.setObjectName("comboBox_TestName")
        self.gridLayout.addWidget(self.comboBox_TestName, 3, 1, 1, 5)
        self.label_TestType = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_TestType.setFont(font)
        self.label_TestType.setObjectName("label_TestType")
        self.gridLayout.addWidget(self.label_TestType, 4, 0, 1, 1)
        self.comboBox_TestType = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_TestType.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_TestType.setObjectName("comboBox_TestType")
        self.gridLayout.addWidget(self.comboBox_TestType, 4, 1, 1, 5)
        self.label_condition = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_condition.setFont(font)
        self.label_condition.setObjectName("label_condition")
        self.gridLayout.addWidget(self.label_condition, 5, 0, 1, 1)
        self.comboBox_condition = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_condition.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_condition.setObjectName("comboBox_condition")
        self.gridLayout.addWidget(self.comboBox_condition, 5, 1, 1, 5)
        self.label_TestStep = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_TestStep.setFont(font)
        self.label_TestStep.setObjectName("label_TestStep")
        self.gridLayout.addWidget(self.label_TestStep, 6, 0, 1, 1)
        self.comboBox_TestStep = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_TestStep.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_TestStep.setObjectName("comboBox_TestStep")
        self.gridLayout.addWidget(self.comboBox_TestStep, 6, 1, 1, 5)
        self.label_expected = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_expected.setFont(font)
        self.label_expected.setObjectName("label_expected")
        self.gridLayout.addWidget(self.label_expected, 7, 0, 1, 1)
        self.comboBox_expected = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_expected.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_expected.setObjectName("comboBox_expected")
        self.gridLayout.addWidget(self.comboBox_expected, 7, 1, 1, 5)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 4)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "表格名称"))
        self.label_ProjectName.setText(_translate("Form", "项目（软件）编号-项目（软件）名称"))
        self.label_TestNumber.setText(_translate("Form", "测试用例标识"))
        self.label_priority.setText(_translate("Form", "优先级"))
        self.label_requirementNumber.setText(_translate("Form", "软件需求/模块标识"))
        self.label_designer.setText(_translate("Form", "用例设计人员"))
        self.label_designTime.setText(_translate("Form", "设计时间"))
        self.label_requirementModel.setText(_translate("Form", "软件需求/模块名称"))
        self.label_TestName.setText(_translate("Form", "用例说明"))
        self.label_TestType.setText(_translate("Form", "测试类型"))
        self.label_condition.setText(_translate("Form", "前提条件"))
        self.label_TestStep.setText(_translate("Form", "测试步骤"))
        self.label_expected.setText(_translate("Form", "预期输出"))

