# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model2_bug.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(824, 576)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 2)
        self.combox_tablename = QtWidgets.QComboBox(self.groupBox)
        self.combox_tablename.setObjectName("combox_tablename")
        self.gridLayout.addWidget(self.combox_tablename, 0, 3, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.combox_bugID = QtWidgets.QComboBox(self.groupBox)
        self.combox_bugID.setObjectName("combox_bugID")
        self.gridLayout.addWidget(self.combox_bugID, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 2)
        self.combox_caseID = QtWidgets.QComboBox(self.groupBox)
        self.combox_caseID.setObjectName("combox_caseID")
        self.gridLayout.addWidget(self.combox_caseID, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 5, 1, 1)
        self.combox_projectname = QtWidgets.QComboBox(self.groupBox)
        self.combox_projectname.setObjectName("combox_projectname")
        self.gridLayout.addWidget(self.combox_projectname, 1, 6, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.combox_bugdate = QtWidgets.QComboBox(self.groupBox)
        self.combox_bugdate.setObjectName("combox_bugdate")
        self.gridLayout.addWidget(self.combox_bugdate, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 2)
        self.combox_bugowner = QtWidgets.QComboBox(self.groupBox)
        self.combox_bugowner.setObjectName("combox_bugowner")
        self.gridLayout.addWidget(self.combox_bugowner, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 5, 1, 1)
        self.combox_version = QtWidgets.QComboBox(self.groupBox)
        self.combox_version.setObjectName("combox_version")
        self.gridLayout.addWidget(self.combox_version, 2, 6, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.combox_bugclass = QtWidgets.QComboBox(self.groupBox)
        self.combox_bugclass.setObjectName("combox_bugclass")
        self.gridLayout.addWidget(self.combox_bugclass, 3, 1, 1, 7)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.combox_buglevel = QtWidgets.QComboBox(self.groupBox)
        self.combox_buglevel.setObjectName("combox_buglevel")
        self.gridLayout.addWidget(self.combox_buglevel, 4, 1, 1, 7)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.combox_bugdescrip = QtWidgets.QComboBox(self.groupBox)
        self.combox_bugdescrip.setObjectName("combox_bugdescrip")
        self.gridLayout.addWidget(self.combox_bugdescrip, 5, 1, 1, 7)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.combox_bugexpect = QtWidgets.QComboBox(self.groupBox)
        self.combox_bugexpect.setObjectName("combox_bugexpect")
        self.gridLayout.addWidget(self.combox_bugexpect, 6, 1, 1, 7)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 0, 1, 1)
        self.combox_fixed = QtWidgets.QComboBox(self.groupBox)
        self.combox_fixed.setObjectName("combox_fixed")
        self.gridLayout.addWidget(self.combox_fixed, 7, 1, 1, 7)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 8, 5, 1, 2)
        self.combox_sign = QtWidgets.QComboBox(self.groupBox)
        self.combox_sign.setObjectName("combox_sign")
        self.gridLayout.addWidget(self.combox_sign, 8, 7, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 9, 6, 1, 1)
        self.combox_signdate = QtWidgets.QComboBox(self.groupBox)
        self.combox_signdate.setObjectName("combox_signdate")
        self.gridLayout.addWidget(self.combox_signdate, 9, 7, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "问题报告单"))
        self.label_2.setText(_translate("Form", "问题标识"))
        self.label_3.setText(_translate("Form", "用例编号"))
        self.label_4.setText(_translate("Form", "项目名称"))
        self.label_5.setText(_translate("Form", "报告日期"))
        self.label_6.setText(_translate("Form", "报告人"))
        self.label_7.setText(_translate("Form", "程序/文档名"))
        self.label_8.setText(_translate("Form", "问题类别"))
        self.label_9.setText(_translate("Form", "问题级别"))
        self.label_10.setText(_translate("Form", "问题描述"))
        self.label_11.setText(_translate("Form", "修改意见"))
        self.label_12.setText(_translate("Form", "设计师意见"))
        self.label_13.setText(_translate("Form", "设计师签名"))
        self.label_14.setText(_translate("Form", "日期"))

