# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model2_testreport.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1005, 794)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.combox_tablename = QtWidgets.QComboBox(self.groupBox)
        self.combox_tablename.setObjectName("combox_tablename")
        self.gridLayout.addWidget(self.combox_tablename, 0, 2, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.combox_casename = QtWidgets.QComboBox(self.groupBox)
        self.combox_casename.setObjectName("combox_casename")
        self.gridLayout.addWidget(self.combox_casename, 1, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.combox_caseID = QtWidgets.QComboBox(self.groupBox)
        self.combox_caseID.setObjectName("combox_caseID")
        self.gridLayout.addWidget(self.combox_caseID, 1, 4, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.combox_requirement = QtWidgets.QComboBox(self.groupBox)
        self.combox_requirement.setObjectName("combox_requirement")
        self.gridLayout.addWidget(self.combox_requirement, 2, 1, 1, 5)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.combox_condition = QtWidgets.QComboBox(self.groupBox)
        self.combox_condition.setObjectName("combox_condition")
        self.gridLayout.addWidget(self.combox_condition, 3, 1, 1, 5)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.combox_casetext = QtWidgets.QComboBox(self.groupBox)
        self.combox_casetext.setObjectName("combox_casetext")
        self.gridLayout.addWidget(self.combox_casetext, 4, 1, 1, 5)
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 5, 0, 1, 1)
        self.combox_testdata = QtWidgets.QComboBox(self.groupBox)
        self.combox_testdata.setObjectName("combox_testdata")
        self.gridLayout.addWidget(self.combox_testdata, 5, 1, 1, 5)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.combox_passcondition = QtWidgets.QComboBox(self.groupBox)
        self.combox_passcondition.setObjectName("combox_passcondition")
        self.gridLayout.addWidget(self.combox_passcondition, 6, 1, 1, 5)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 6)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.label_input = QtWidgets.QLabel(self.groupBox)
        self.label_input.setObjectName("label_input")
        self.gridLayout.addWidget(self.label_input, 8, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 3, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 8, 5, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 9, 0, 1, 1)
        self.combox_input = QtWidgets.QComboBox(self.groupBox)
        self.combox_input.setObjectName("combox_input")
        self.gridLayout.addWidget(self.combox_input, 9, 1, 1, 1)
        self.combox_expect = QtWidgets.QComboBox(self.groupBox)
        self.combox_expect.setObjectName("combox_expect")
        self.gridLayout.addWidget(self.combox_expect, 9, 2, 1, 1)
        self.combox_result = QtWidgets.QComboBox(self.groupBox)
        self.combox_result.setObjectName("combox_result")
        self.gridLayout.addWidget(self.combox_result, 9, 3, 1, 2)
        self.combox_ispass = QtWidgets.QComboBox(self.groupBox)
        self.combox_ispass.setObjectName("combox_ispass")
        self.gridLayout.addWidget(self.combox_ispass, 9, 5, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 10, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.groupBox)
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 10, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.groupBox)
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 10, 2, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.groupBox)
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 10, 4, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.groupBox)
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 10, 5, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 11, 0, 1, 1)
        self.combox_totalresult = QtWidgets.QComboBox(self.groupBox)
        self.combox_totalresult.setObjectName("combox_totalresult")
        self.gridLayout.addWidget(self.combox_totalresult, 11, 1, 1, 5)
        self.label_29 = QtWidgets.QLabel(self.groupBox)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 12, 0, 1, 1)
        self.combox_bugID = QtWidgets.QComboBox(self.groupBox)
        self.combox_bugID.setObjectName("combox_bugID")
        self.gridLayout.addWidget(self.combox_bugID, 12, 1, 1, 5)
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 13, 0, 1, 1)
        self.combox_testman = QtWidgets.QComboBox(self.groupBox)
        self.combox_testman.setObjectName("combox_testman")
        self.gridLayout.addWidget(self.combox_testman, 13, 1, 1, 5)
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 14, 0, 1, 1)
        self.combox_testtime = QtWidgets.QComboBox(self.groupBox)
        self.combox_testtime.setObjectName("combox_testtime")
        self.gridLayout.addWidget(self.combox_testtime, 14, 1, 1, 5)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "表格名称"))
        self.label_2.setText(_translate("Form", "测试用例名称"))
        self.label_4.setText(_translate("Form", "标识"))
        self.label_3.setText(_translate("Form", "需求追踪"))
        self.label_5.setText(_translate("Form", "先决条件"))
        self.label_6.setText(_translate("Form", "测试用例综述"))
        self.label_32.setText(_translate("Form", "测试数据"))
        self.label_7.setText(_translate("Form", "通过准则"))
        self.label_8.setText(_translate("Form", "测试步骤"))
        self.label_9.setText(_translate("Form", "序号"))
        self.label_input.setText(_translate("Form", "输入及操作"))
        self.label_11.setText(_translate("Form", "期望结果"))
        self.label_12.setText(_translate("Form", "实测结果"))
        self.label_13.setText(_translate("Form", "通过与否"))
        self.label_27.setText(_translate("Form", "1"))
        self.label_33.setText(_translate("Form", "<html><head/><body><p>。</p><p>。</p><p>。</p></body></html>"))
        self.label_54.setText(_translate("Form", "<html><head/><body><p>。</p><p>。</p><p>。</p></body></html>"))
        self.label_55.setText(_translate("Form", "<html><head/><body><p>。</p><p>。</p><p>。</p></body></html>"))
        self.label_56.setText(_translate("Form", "<html><head/><body><p>。</p><p>。</p><p>。</p></body></html>"))
        self.label_57.setText(_translate("Form", "<html><head/><body><p>。</p><p>。</p><p>。</p></body></html>"))
        self.label_28.setText(_translate("Form", "执行结果"))
        self.label_29.setText(_translate("Form", "问题标识单"))
        self.label_30.setText(_translate("Form", "测试人员"))
        self.label_31.setText(_translate("Form", "测试时间"))

