# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectexcel.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(465, 515)
        self.gridLayout_2 = QtWidgets.QGridLayout(WizardPage)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setObjectName("gridLayout")
        self.label_step1 = QtWidgets.QLabel(WizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_step1.sizePolicy().hasHeightForWidth())
        self.label_step1.setSizePolicy(sizePolicy)
        self.label_step1.setMinimumSize(QtCore.QSize(0, 0))
        self.label_step1.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step1.setFont(font)
        self.label_step1.setObjectName("label_step1")
        self.gridLayout.addWidget(self.label_step1, 0, 0, 1, 2)
        self.pathLabel = QtWidgets.QLabel(WizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLabel.sizePolicy().hasHeightForWidth())
        self.pathLabel.setSizePolicy(sizePolicy)
        self.pathLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.pathLabel.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.pathLabel.setFont(font)
        self.pathLabel.setObjectName("pathLabel")
        self.gridLayout.addWidget(self.pathLabel, 1, 0, 1, 1)
        self.lePath = QtWidgets.QLineEdit(WizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lePath.sizePolicy().hasHeightForWidth())
        self.lePath.setSizePolicy(sizePolicy)
        self.lePath.setMinimumSize(QtCore.QSize(260, 0))
        self.lePath.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lePath.setObjectName("lePath")
        self.gridLayout.addWidget(self.lePath, 1, 1, 1, 1)
        self.pBtnChoosePath = QtWidgets.QPushButton(WizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBtnChoosePath.sizePolicy().hasHeightForWidth())
        self.pBtnChoosePath.setSizePolicy(sizePolicy)
        self.pBtnChoosePath.setMinimumSize(QtCore.QSize(0, 0))
        self.pBtnChoosePath.setMaximumSize(QtCore.QSize(65, 35))
        self.pBtnChoosePath.setObjectName("pBtnChoosePath")
        self.gridLayout.addWidget(self.pBtnChoosePath, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.label_step2 = QtWidgets.QLabel(WizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_step2.sizePolicy().hasHeightForWidth())
        self.label_step2.setSizePolicy(sizePolicy)
        self.label_step2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_step2.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2.setFont(font)
        self.label_step2.setObjectName("label_step2")
        self.gridLayout.addWidget(self.label_step2, 2, 0, 1, 2)
        self.groupBox_workbook = QtWidgets.QGroupBox(WizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_workbook.sizePolicy().hasHeightForWidth())
        self.groupBox_workbook.setSizePolicy(sizePolicy)
        self.groupBox_workbook.setMinimumSize(QtCore.QSize(320, 400))
        self.groupBox_workbook.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_workbook.setObjectName("groupBox_workbook")
        self.gridLayout.addWidget(self.groupBox_workbook, 3, 0, 1, 4)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.labErrTip = QtWidgets.QLabel(WizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labErrTip.sizePolicy().hasHeightForWidth())
        self.labErrTip.setSizePolicy(sizePolicy)
        self.labErrTip.setMinimumSize(QtCore.QSize(0, 0))
        self.labErrTip.setMaximumSize(QtCore.QSize(16777215, 35))
        self.labErrTip.setStyleSheet("color:rgb(255, 0, 0)")
        self.labErrTip.setText("")
        self.labErrTip.setObjectName("labErrTip")
        self.gridLayout_2.addWidget(self.labErrTip, 1, 0, 1, 1)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        self.label_step1.setText(_translate("WizardPage", "1.选择需要装换的Excel文件"))
        self.pathLabel.setText(_translate("WizardPage", "文件路径"))
        self.pBtnChoosePath.setText(_translate("WizardPage", "选择文件"))
        self.label_step2.setText(_translate("WizardPage", "2.选择工作表"))
        self.groupBox_workbook.setTitle(_translate("WizardPage", "选择工作表"))

